package com.commons.data.entity;

import com.commons.data.dao.dto.CustomGeoJsonPolygon;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.geo.GeoJsonPolygon;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.List;

@Document(collection = "Project")
@Data
public class Project extends BaseEntity
{
    @Transient
    public static final String SEQUENCE_NAME = "Project";
    private  String classname;
    @Id
    private Long id;
    private String name;
    private String desc;
//    @Indexed(unique = true)
    private String code; // autogenerated through name
    private String projecthirarichalcode;
    private String parentproject;
    private String address;
    private List<MMU> mmulist;
    private List<ProjectMember> projectteam;
    private PinCode pinCode;
    private WareHouseMaster warehouse;
    private String type;
    private CustomGeoJsonPolygon polygoncoordinates;
    private String transaction_id;
    private String laststatus;
    private String progress;
    private String processed_datasets;
    private String total_datasets;

    public void setClassname(String classname) {
        this.classname = "Project";
    }

}
