package com.commons.util.model.dto;

import com.commons.data.dao.dto.CustomGeoJsonPolygon;
import com.commons.data.entity.*;
import lombok.Data;
import org.springframework.data.mongodb.core.index.Indexed;

import java.util.List;


@Data
public class ProjectDTO extends BaseDtoI{

    private String name;
    private String desc;
    @Indexed(unique = true)
    private String code; // autogenerated through name
    private String projecthirarichalcode;
    private String parentproject;
    private String address;
    private List<MMU> mmulist;
    private MMUCreation mmucreation;
    private List<ProjectMember> projectteam;
    private PinCode pinCode;
    private WareHouseMaster warehouse;
    private String type;
    private CustomGeoJsonPolygon polygoncoordinates;
    private String transaction_id;
    private String laststatus;
    private String progress;
    private String processed_datasets;
    private String total_datasets;

    private  String classname;

}
